# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: asanni <asanni@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/11/02 15:19:34 by asanni            #+#    #+#              #
#    Updated: 2024/11/02 17:03:58 by asanni           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #


NAME = megaphone

CFLAGS = -Wall -Werror -Wextra

SOURCES = megaphone.cpp

COMPILE = c++

all:
	$(COMPILE) $(SOURCES) $(CFLAGS) -o $(NAME)
