# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: asanni <asanni@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/11/23 17:08:41 by asanni            #+#    #+#              #
#    Updated: 2024/11/27 17:52:03 by asanni           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #


NAME = zombie
CFLAGS = -Wall -Werror -Wextra
COMPILE = c++ -std=c++98


CPP = $(wildcard *.cpp)
HPP = $(wildcard *.hpp)

all:
	$(COMPILE) $(CPP) $(CFLAGS) -o $(NAME)
