# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: asanni <asanni@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/03/15 14:14:46 by asanni            #+#    #+#              #
#    Updated: 2025/03/16 12:36:45 by asanni           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ex02
CFLAGS = -Wall -Werror -Wextra
COMPILE = c++ -std=c++98


CPP = $(wildcard *.cpp)
HPP = $(wildcard *.hpp)

all:
	$(COMPILE) $(CPP) $(CFLAGS) -o $(NAME)
