# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: asanni <asanni@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/12/14 16:40:05 by asanni            #+#    #+#              #
#    Updated: 2025/01/09 19:49:18 by asanni           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = brain
CFLAGS = -Wall -Werror -Wextra
COMPILE = c++ -std=c++98


CPP = $(wildcard *.cpp)

all:
	$(COMPILE) $(CPP) $(CFLAGS) -o $(NAME)
