# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: asanni <asanni@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/11/02 16:20:40 by asanni            #+#    #+#              #
#    Updated: 2024/11/02 17:03:46 by asanni           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = phone_book

CFLAGS = -Wall -Werror -Wextra

SOURCES = *.cpp

COMPILE = c++

all:
	$(COMPILE) $(SOURCES) $(CFLAGS) -o $(NAME)
